; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "MoleGraph"
#define MyAppVersion "4.3-beta3"
#define MyAppPublisher "e-Mole"
#define MyAppURL "https://www.molegraph.eu"
#define MyAppExeName "MoleGraph.exe"
#define MyAppAssocName MyAppName + " File"
#define MyAppAssocExt ".mogr"
#define MyAppAssocKey StringChange(MyAppAssocName, " ", "") + MyAppAssocExt

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{42F4A541-54A9-448B-8D3D-CF5AD95CAF4D}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
ChangesAssociations=yes
DisableProgramGroupPage=yes
LicenseFile=LICENSE.txt
; Uncomment the following line to run in non administrative install mode (install for current user only.)
;PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
OutputDir=deploy
OutputBaseFilename=MoleGraph-Installer
SetupIconFile=MoleGraph.ico
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"; LicenseFile: "installer_assets\license-en.txt"
Name: "czech"; MessagesFile: "compiler:Languages\Czech.isl"; LicenseFile: "installer_assets\license-cs.txt"
Name: "polish"; MessagesFile: "compiler:Languages\Polish.isl"; LicenseFile: "installer_assets\license-pl.txt"
Name: "italian"; MessagesFile: "compiler:Languages\Italian.isl"; LicenseFile: "installer_assets\license-it.txt"
Name: "spanish"; MessagesFile: "compiler:Languages\Spanish.isl"; LicenseFile: "installer_assets\license-es.txt"
Name: "portuguese"; MessagesFile: "compiler:Languages\Portuguese.isl"; LicenseFile: "installer_assets\license-pt.txt"
Name: "french"; MessagesFile: "compiler:Languages\French.isl"; LicenseFile: "installer_assets\license-fr.txt"
Name: "hungarian"; MessagesFile: "compiler:Languages\Hungarian.isl"; LicenseFile: "installer_assets\license-hu.txt"
Name: "german"; MessagesFile: "compiler:Languages\German.isl"; LicenseFile: "installer_assets\license-de.txt"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "deploy\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; Přidáme kopírování textových licencí (uživatel dostane na disk obě)
Source: "installer_assets\license-en.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "installer_assets\license-cs.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "installer_assets\license-pl.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "installer_assets\license-it.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "installer_assets\license-es.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "installer_assets\license-pt.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "installer_assets\license-fr.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "installer_assets\license-hu.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "installer_assets\license-de.txt"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Registry]
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocExt}\OpenWithProgids"; ValueType: string; ValueName: "{#MyAppAssocKey}"; ValueData: ""; Flags: uninsdeletevalue
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}"; ValueType: string; ValueName: ""; ValueData: "{#MyAppAssocName}"; Flags: uninsdeletekey
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\{#MyAppExeName},0"
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\{#MyAppExeName}"" ""%1"""
Root: HKA; Subkey: "Software\Classes\Applications\{#MyAppExeName}\SupportedTypes"; ValueType: string; ValueName: ".myp"; ValueData: ""

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent