name: Build MoleGraph App (Windows Test)

# Kdy se má akce spustit:
on:
  push:
    tags:
      - 'v*' # Spustí kompilaci POUZE tehdy, když se vytvoří tag začínající na "v"
  workflow_dispatch: # Ponechá možnost spouštět to ručně tlačítkem z webu

jobs:
  build-windows:
    name: Kompilace pro Windows (Qt 5.15)
    runs-on: windows-latest

    steps:
      - name: Checkout kód
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # <--- TOHLE POTŘEBUJEME PRO SKRIPT

      - name: Instalace Qt 5.15.2 (MinGW)
        uses: jurplel/install-qt-action@v4
        with:
          version: '5.15.2'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_mingw81' # Použijeme MinGW kompilátor

      - name: Vytvoř Build složku
        run: mkdir build
        working-directory: ./SerialToGraph

      - name: Qmake konfigurace
        run: qmake ../SerialToGraph.pro CONFIG+=release
        working-directory: ./SerialToGraph/build

      - name: Kompilace (mingw32-make)
        run: mingw32-make
        working-directory: ./SerialToGraph/build

      - name: Příprava čistého balíčku (windeployqt)
        working-directory: ./SerialToGraph
        run: |
          # 1. Vytvoří čistou složku deploy hned vedle installer.iss
          mkdir deploy
          
          # 2. Vyzvedne čistý EXE soubor z build/release a vloží ho do deploy
          Copy-Item -Path "build\release\MoleGraph.exe" -Destination "deploy\"
          
          # 3. Nakopíruje senzory (ze SerialToGraph)
          Copy-Item -Path "sensors" -Destination "deploy\sensors" -Recurse
          
          # 4. Vloží licenci do deploy
          Copy-Item -Path "LICENSE.txt" -Destination "deploy\"
          
          # 5. Necháme Qt přibalit DLL knihovny PŘÍMO k .exe do složky deploy/
          windeployqt deploy/MoleGraph.exe
          
          # 6. Smažeme 35MB zbytečného balastu z Qt
          Remove-Item -Path "deploy\translations" -Recurse -Force -ErrorAction SilentlyContinue
          Remove-Item -Path "deploy\D3Dcompiler_47.dll" -Force -ErrorAction SilentlyContinue
          Remove-Item -Path "deploy\libGLESv2.dll" -Force -ErrorAction SilentlyContinue
          Remove-Item -Path "deploy\opengl32sw.dll" -Force -ErrorAction SilentlyContinue
          Remove-Item -Path "deploy\libEGL.dll" -Force -ErrorAction SilentlyContinue

      - name: Kompilace Inno Setup Instalátoru
        working-directory: ./SerialToGraph
        run: |
          # Složka deploy je připravená plná čistých dat, můžeme rovnou balit!
          iscc installer.iss        

      - name: Ulož výsledek jako Artefakt
        uses: actions/upload-artifact@v4
        with:
          name: MoleGraph-Windows
          # Artefakt se uloží z Output složky nebo z deploy, podle toho kam Inno Setup zapisuje výsledek
          path: SerialToGraph/deploy/MoleGraph-Installer.exe
