name: Build MoleGraph App (macOS Test)

on:
  push:
    tags:
      - 'v*' # Spustí kompilaci POUZE tehdy, když se vytvoří tag začínající na "v"
  workflow_dispatch: # Ponechá možnost spouštět to ručně tlačítkem z webu

jobs:
  build-mac:
    name: Kompilace pro macOS (Qt 5.15)
    runs-on: macos-latest 

    steps:
      - name: Stáhnutí kódu (Checkout)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # Stáhne i historii a tagy pro git describe

      - name: Instalace Qt 5.15.2
        uses: jurplel/install-qt-action@v4
        with:
          version: '5.15.2'
          host: 'mac'
          target: 'desktop'

      - name: Vytvoř Build složku
        run: mkdir build
        working-directory: ./SerialToGraph

      - name: Qmake konfigurace
        # Změnili jsme jen tento jeden řádek, přidali jsme QMAKE_LIBS_OPENGL
        run: qmake ../SerialToGraph.pro CONFIG+=release "QMAKE_LIBS_OPENGL = -framework OpenGL"
        working-directory: ./SerialToGraph/build

      - name: Kompilace (make)
        # sysctl -n hw.ncpu zjistí počet jader na Macu a urychlí kompilaci
        run: make -j$(sysctl -n hw.ncpu)
        working-directory: ./SerialToGraph/build

      - name: Zabalení pro Mac (macdeployqt)
        run: |
          # Nakopíruje složku sensors dovnitř .app svazku
          cp -r ../sensors MoleGraph.app/Contents/MacOS/
          
          # macdeployqt vezme hotovou aplikaci, narve do ní knihovny a vyrobí DMG
          macdeployqt MoleGraph.app -dmg
        working-directory: ./SerialToGraph/build

      - name: Ulož výsledek jako Artefakt
        uses: actions/upload-artifact@v4
        with:
          name: MoleGraph-macOS
          path: SerialToGraph/build/*.dmg
